name: 🐛 Bug report
description: Report incorrect or unexpected behavior of venok modules
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
    validations:
      required: true
      
  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search to see if an issue already exists for the bug you encountered"
      options:
      - label: "I have searched the existing issues"
        required: true
      
  - type: input
    validations:
      required: true
    attributes:
      label: "Minimum reproduction code"
      description: "An URL to some Git repository"
      placeholder: "https://github.com/..."

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: |
        How the issue manifests?
        You could leave this blank if you alread write this in your reproduction code
      placeholder: |
        1. `npm ci`
        2. `npm start:dev`
        3. See error...
      
  - type: input
    id: Venok-module-version
    attributes:
      label: Venok-module version
      description: Which version of Venok-module are you using?
    validations:
      required: true
      
  - type: input
    id: nestjs-version
    attributes:
      label: nest.js version
      description: Which version of nest.js are you using?
      placeholder: 10.x.x
    validations:
      required: true
      
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
      placeholder: Node.js version 18+ is required
    validations:
      required: true
      
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
